// snarkjs Groth16 → groth16-solana byte layout (from the spike's to_solana.js):
//   G1 = x_be(32) || y_be(32); G2 = x.c1 || x.c0 || y.c1 || y.c0 (each 32-byte big-endian);
//   proof A is negated (y → p − y) because the verifier checks e(−A,B)·e(L,γ)·e(C,δ)·e(α,β) = 1.
const P = 21888242871839275222246405745257275088696311157297823662689037894645226208583n;

export const be32 = (x) => {
  const out = new Uint8Array(32);
  let v = BigInt(x);
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out;
};
const cat = (...parts) => {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let o = 0;
  for (const p of parts) {
    out.set(p, o);
    o += p.length;
  }
  return out;
};
export const g1 = (p) => cat(be32(p[0]), be32(p[1]));
export const g1neg = (p) => cat(be32(p[0]), be32((P - BigInt(p[1])) % P));
export const g2 = (p) => cat(be32(p[0][1]), be32(p[0][0]), be32(p[1][1]), be32(p[1][0]));

/** A snarkjs proof + public signals → { a, b, c, inputs } byte arrays for the program. */
export function proofToSolana(proof, publicSignals) {
  return {
    a: g1neg(proof.pi_a),
    b: g2(proof.pi_b),
    c: g1(proof.pi_c),
    inputs: publicSignals.map(be32),
  };
}

const arr = (bytes) => `[${Array.from(bytes).join(", ")}]`;

/** Render a snarkjs verifying key as a groth16-solana `Groth16Verifyingkey` constant. */
export function vkToRust(name, vk, note) {
  return `// Generated by circuits/scripts — do not edit. ${note}
use groth16_solana::groth16::Groth16Verifyingkey;

pub const ${name}: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${vk.nPublic},
    vk_alpha_g1: ${arr(g1(vk.vk_alpha_1))},
    vk_beta_g2: ${arr(g2(vk.vk_beta_2))},
    vk_gamme_g2: ${arr(g2(vk.vk_gamma_2))},
    vk_delta_g2: ${arr(g2(vk.vk_delta_2))},
    vk_ic: &[
${vk.IC.map((p) => `        ${arr(g1(p))},`).join("\n")}
    ],
};
`;
}
