/**
 * One-time devnet setup after `anchor deploy` (architecture 12.4 "deploy-program"):
 *   1. the kUSD test mint (6 decimals; the admin is the faucet's mint authority)
 *   2. the Kitty config (fees, demo timings, the Anon Aadhaar test key, dev registration on)
 *   3. a seeded House Fund
 *   4. a relay/Butler wallet with some SOL
 * Writes backend/.env.local (secrets; gitignored) and prints the app's env.
 *
 *   ADMIN_KEYPAIR=~/.config/solana/id.json tsx scripts/setup-devnet.ts
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { generateKeyPairSigner, getAddressEncoder, lamports, createKeyPairSignerFromBytes, createKeyPairSignerFromPrivateKeyBytes } from "@solana/kit";
import { getCreateAccountInstruction, getTransferSolInstruction } from "@solana-program/system";
import {
  TOKEN_PROGRAM_ADDRESS,
  findAssociatedTokenPda,
  getCreateAssociatedTokenIdempotentInstruction,
  getInitializeMint2Instruction,
  getMintSize,
  getMintToInstruction,
} from "@solana-program/token";
import * as C from "@kitty/chain";
import * as Z from "@kitty/zk";
import { fetchConfig, rpc, sendInstructions } from "../src/chain";

const USD = 1_000_000n;
const path = (p: string) => p.replace(/^~/, homedir());
const kp = async (p: string) => createKeyPairSignerFromBytes(Uint8Array.from(JSON.parse(readFileSync(path(p), "utf8"))));
const secretOf = (seed: Uint8Array, address: string) => JSON.stringify([...seed, ...getAddressEncoder().encode(address as never)]);

const admin = await kp(process.env.ADMIN_KEYPAIR ?? "~/.config/solana/id.json");
console.log(`admin ${admin.address}`);

const existing = await fetchConfig();
if (existing) {
  console.log(`already initialised: mint ${existing.mint}, next party ${existing.nextPartyId}`);
  process.exit(0);
}

// 1. kUSD
const mint = await generateKeyPairSigner();
const rent = await rpc.getMinimumBalanceForRentExemption(BigInt(getMintSize())).send();
await sendInstructions(admin, [
  getCreateAccountInstruction({ payer: admin, newAccount: mint, lamports: rent, space: getMintSize(), programAddress: TOKEN_PROGRAM_ADDRESS }),
  getInitializeMint2Instruction({ mint: mint.address, decimals: 6, mintAuthority: admin.address }),
]);
const [treasury] = await findAssociatedTokenPda({ owner: admin.address, mint: mint.address, tokenProgram: TOKEN_PROGRAM_ADDRESS });
await sendInstructions(admin, [
  getCreateAssociatedTokenIdempotentInstruction({ payer: admin, ata: treasury, owner: admin.address, mint: mint.address }),
  getMintToInstruction({ mint: mint.address, token: treasury, mintAuthority: admin, amount: 20_000n * USD }),
]);
console.log(`kUSD mint ${mint.address}`);

// 2. config
await sendInstructions(admin, [
  await C.getInitializeInstructionAsync({
    admin,
    mint: mint.address,
    treasury,
    args: {
      protocolBps: 50, coverBps: 50, lateBps: 200, maxHostBps: 200,
      minGraceSecs: 60n, collectWindowSecs: 30n, nowToleranceSecs: 120n,
      allowance: 150n * USD,
      aadhaarPubkeyHash: Z.bigToBytes32(C.AADHAAR_TEST_PUBKEY_HASH),
      nullifierSeed: C.KITTY_NULLIFIER_SEED,
      devRegister: true,
      paused: false,
    },
  }),
], 400_000);
console.log("config initialised");

// 3. House Fund seed
await sendInstructions(admin, [
  await C.getHouseDepositInstructionAsync({ owner: admin, ownerToken: treasury, share: await C.sharePda(admin.address), amount: 10_000n * USD }),
]);
console.log("House Fund seeded with 10,000 kUSD");

// 4. relay / Butler wallet
const relaySeed = crypto.getRandomValues(new Uint8Array(32));
const relay = await createKeyPairSignerFromPrivateKeyBytes(relaySeed);
await sendInstructions(admin, [getTransferSolInstruction({ source: admin, destination: relay.address, amount: lamports(BigInt(Number(process.env.RELAY_SOL ?? "0.4") * 1e9)) })]);
console.log(`relay ${relay.address}`);

const env = `# Generated by scripts/setup-devnet.ts on ${new Date().toISOString()}. Secrets: never commit.
KITTY_PROGRAM_ID=${C.KITTY_PROGRAM_ADDRESS}
KITTY_MINT=${mint.address}
RELAY_KEYPAIR=${secretOf(relaySeed, relay.address)}
FAUCET_KEYPAIR=${JSON.stringify(Array.from(JSON.parse(readFileSync(path(process.env.ADMIN_KEYPAIR ?? "~/.config/solana/id.json"), "utf8"))))}
`;
const out = new URL("../.env.local", import.meta.url);
if (existsSync(out)) writeFileSync(new URL("../.env.local.bak", import.meta.url), readFileSync(out));
writeFileSync(out, env);
console.log(`
wrote backend/.env.local

App env (frontend/apps/web/.env.local):
NEXT_PUBLIC_KITTY_API=http://localhost:8787
NEXT_PUBLIC_KITTY_PROGRAM_ID=${C.KITTY_PROGRAM_ADDRESS}
NEXT_PUBLIC_KITTY_MINT=${mint.address}
NEXT_PUBLIC_SOLANA_RPC=https://api.devnet.solana.com
`);
