import { chromium } from "@playwright/test";
const out = process.env.SHOTS ?? "../../review";
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p = await c.newPage();
p.on("pageerror", (e) => console.log("ERR", e.message));
await p.goto("http://localhost:3100/pass", { waitUntil: "networkidle" });
await p.fill('input[type="email"]', "guest@kitty.test");
await p.click('button[type="submit"]');
await p.waitForTimeout(600);
await p.setInputFiles('input[type="file"]', "../../docs/ref/logo-concept.png");
await p.waitForTimeout(1600);
await p.screenshot({ path: `${out}/pass-qr.png` });
await p.getByRole("button", { name: "Make my pass" }).click();
await p.waitForTimeout(2500);
await p.screenshot({ path: `${out}/pass-keys.png` });
await p.waitForTimeout(6000);
await p.screenshot({ path: `${out}/pass-proof.png` });
await p.waitForTimeout(6500);
await p.screenshot({ path: `${out}/pass-done.png` });
await b.close();
